### ISSUE TITLE
Doesn't hide Evolution's titlebar on GNOME 3.36.1 Wayland

### ISSUE THREAD

**Issue by abdulocracy** [velitasali/GTKTitleBar#21]
The title pretty much says it. Can't find anything in the logs.

**Comment by velitasali** [comment]
Windows that report that they are decorating the title bar are not hidden and for otherwise to be the case, whitelists or similar feature needs to be in place which is not at the moment.

So, I would say this is evolution's mistake to report false positive. 

![Screenshot from 2020-04-09 19-28-44](https://user-images.githubusercontent.com/10258162/78918026-6b2dc200-7a98-11ea-9d56-e9dec0694ca0.png)
